version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sirius
      POSTGRES_USER: siriususer
      POSTGRES_PASSWORD: siriuspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./back
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./back/.env

  frontend:
    build: ./front
    ports:
      - "3000:80"
    restart: always

volumes:
  postgres_data:
