version: '3.8'

services:
  backend:
    build: ./back
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build: ./front
    ports:
      - "3000:80"
    restart: always
